navbar-links:
    About: /About-Me/
    Archive: /archives

avatar: /img/avartar.jpg
favicon: /img/favicon.png

header:
    title: "Xuankang Lin"
    motto: "See the world as it is, and love it."

    # bigimgs:
    #     - src: /bigimgs/01.jpg
    #       desc: beautiful island
    #     - src: /bigimgs/02.jpg
    #       desc: Tropical Fish
    #     - src: /bigimgs/03.jpg
    #       desc: ocean

rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

highlight:
  enable: true
# or use any highlight.js style
#  style_path: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/default.min.css"
  style_path: "/css/highlight.css"

footer:
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: true
  mail:
    link: 'mailto:xuankang.lin@gmail.com'
    title: Email me
    icon: fa-envelope
    enable: true
  linkedin:
    link: 'https://www.linkedin.com/in/xuankanglin/'
    title: LinkedIn
    icon: fa-linkedin
    enable: true
  github:
    link: 'https://github.com/XuankangLin'
    title: GitHub
    icon: fa-github
    enable: true
  weibo:
    link: 'https://weibo.com/andriylin/'
    title: Weibo
    icon: fa-weibo
    enable: true
  douban:
    link: 'https://www.douban.com/people/andriylin/'
    title: Douban
    icon: fa-douban
    enable: true
  goodreads:
    link: 'https://www.goodreads.com/xuankanglin'
    title: Goodreads
    icon: fa-goodreads
    enable: true
  facebook:
    link: # your link e.g. https://...
    title: Facebook
    icon: fa-facebook
    enable: false
  twitter:
    link: 'https://twitter.com/XuankangLin'
    title: Twitter
    icon: fa-twitter
    enable: false
  instagram:
    link: 'https://www.instagram.com/verified_andriy/'
    title: Instagram
    icon: fa-instagram
    enable: false
  stackoverflow:
    link: # your link here e.g. http...
    title: StackOverflow
    icon: fa-stack-overflow
    enable: false

google_analytics:
  enable: true
  id: UA-42282594-1  ## e.g. UA-1766729-8 your google analytics ID.
  site: auto ## e.g. yangjian.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

comment:
  # false, disqus, netease or facebook
  enable: disqus
  # disqus user, netease productKey or facebook appid
  id: andriylin-blog
  # # [facebook only] plugin language
  # lang: en_US
  # # [facebook only] number of posts per load
  # numposts: 10

# IMPORTANT NOTE [Facebook Plugin]:
# If you are using Facebook Social Plugin and it's not working,
# please go to this URL https://developers.facebook.com/tools/debug/og/object/
# copy the link of your post there and press the button "Fetch new scrape information".
# In that way, you are going to update your post metatags Facebook Open Graph information.
